# Generated by Django 5.1.6 on 2025-02-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
