# Generated by Django 5.1.6 on 2025-02-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_studentexam_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentexam',
            old_name='Course',
            new_name='course',
        ),
    ]
