# Generated by Django 5.1.6 on 2025-02-05 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_course_studentexam_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.course')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.unit')),
            ],
        ),
    ]
