# Generated by Django 5.1.6 on 2025-02-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_unit_course_courseunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='cat_mark',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam_mark',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='project_mark',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
