# Generated by Django 5.1.6 on 2025-02-09 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_studentexam_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexam',
            name='course',
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.studentexam')),
            ],
        ),
    ]
