# Generated by Django 5.1.6 on 2025-02-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_studentexam_course_studentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.course'),
        ),
        migrations.CreateModel(
            name='StudentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.series')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.studentexam')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
