# Generated by Django 5.1.6 on 2025-02-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_studentexam_course_studentseries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
